Ajout des fichiers Template SQL pour commencer le travail.
xxvetxx/GIS811 pull request #1
Opened 2022-09-20 18:48 UTC by Lucien-BR

J'ai mis un gitignore pour .idea/, car Jasmyn n'a pas push le siens. Puis j'ajoute un folder avec 8 scripts à l'intérieur.

2022-09-20 22:24 UTC, xxvetxx requested changes

2022-09-20 22:24 UTC, xxvetxx commented on .gitignore
> +.idea/
tu semble avoir un problème un problème ici puisque tu as push le .idea mais sous ScriptsSQL quand même. Je viens de réussir à mettre mes 2 ssh et j'ai fait un PR sans voir la tienne. Je te propose d'enlever ce commit et de juste garder ton autre avec tes scripts et de prendre mon git ignore (identique mais tu aura pas le bug du .idea dans des subs folders. Sinon il faudrait un wildcard (*) avant le .idea

2022-09-23 16:16 UTC, Lucien-BR commented on .gitignore
> +.idea/
Bonne idée, laisse moi voir comment je peux retirer un commit de la PR, je te reviens avec ca.

2022-09-23 17:56 UTC, xxvetxx approved these changes

2022-09-23 17:56 UTC, merged